### ISSUE TITLE
Cannot read property '~' of undefined

### ISSUE THREAD

**Issue by dacodekid** [windicss/windicss-webpack-plugin#35]
I just came to know about `windicss` and tried to use it with `webpack` - but receiving this below error.

```
[webpack-cli] TypeError: Cannot read property '~' of undefined
    at WindiCSSWebpackPlugin.apply (/Users/codekid/dev/windi-test/node_modules/windicss-webpack-plugin/dist/plugin.js:31:116)
    at createCompiler (/Users/codekid/dev/windi-test/node_modules/webpack/lib/webpack.js:71:12)
    at create (/Users/codekid/dev/windi-test/node_modules/webpack/lib/webpack.js:118:16)
    at webpack (/Users/codekid/dev/windi-test/node_modules/webpack/lib/webpack.js:142:32)
    at WebpackCLI.f [as webpack] (/Users/codekid/dev/windi-test/node_modules/webpack/lib/index.js:54:15)
    at WebpackCLI.createCompiler (/Users/codekid/dev/windi-test/node_modules/webpack-cli/lib/webpack-cli.js:1847:29)
    at async Command.<anonymous> (/Users/codekid/dev/windi-test/node_modules/@webpack-cli/serve/lib/index.js:68:30)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/codekid/dev/windi-test/node_modules/webpack-cli/lib/webpack-cli.js:1284:13)
```

Here is the `package.json`
```json
{
  "devDependencies": {
    "html-webpack-plugin": "^5.3.1",
    "webpack": "^5.31.2",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2",
    "windicss-webpack-plugin": "^0.3.3"
  },
  "scripts": {
    "dev": "webpack serve"
  }
}
```

And `webpack.config.js` file

```js
const WebpackWindiCSSPlugin = require('windicss-webpack-plugin').default;

module.exports = {
  plugins: [new WebpackWindiCSSPlugin()],
};
```

*Environment:*
```
OS : macOS Big Sur
```

I tried to create a sample project in different level of `webpack.config.js` code but, it always breaks at this level.  Am I missing anything?

**Comment by dacodekid** [comment]
I was able to fix it with

```js
    new WindiCSSWebpacPlugin({
      root: './',
    }),
```
