### ISSUE TITLE
Error: Cannot find module '../../dist/index.js'

### ISSUE THREAD

**Issue by theodorusclarence** [windicss/windicss-webpack-plugin#68]
**Describe the bug**
Can't start dev server

**To Reproduce**
1. Create a new Next.js App from create-next-app then follow the structure on the example
2. Run the dev server

```
Error: Cannot find module '../../dist/index.js'
Require stack:
- /Users/Clarence/Web and Course/2 - Learning/learn-windicss/next.config.js
- /Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/next-server/server/config.js
- /Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/server/next.js
- /Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/server/lib/start-server.js
- /Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/cli/next-dev.js
- /Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/build/webpack/require-hook.js:4:1784)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Clarence/Web and Course/2 - Learning/learn-windicss/next.config.js:1:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Clarence/Web and Course/2 - Learning/learn-windicss/next.config.js',
    '/Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/next-server/server/config.js',
    '/Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/server/next.js',
    '/Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/server/lib/start-server.js',
    '/Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/cli/next-dev.js',
    '/Users/Clarence/Web and Course/2 - Learning/learn-windicss/node_modules/next/dist/bin/next'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by theodorusclarence** [comment]
```
const WindiCSSWebpackPlugin = require('windicss-webpack-plugin').default;
```

Solved by changing the ../../dist/index.js to the import

Was I supposed to do that? 😅
