### ISSUE TITLE
[webpack-cli] Promise rejection: TypeError: WindiCSS is not a constructor

### ISSUE THREAD

**Issue by lautiamkok** [windicss/windicss-webpack-plugin#84]
Following the installation guide here https://windicss.org/integrations/webpack.html for webpack, I get the following error:

```
[webpack-cli] Promise rejection: TypeError: WindiCSS is not a constructor
[webpack-cli] TypeError: WindiCSS is not a constructor
    at Object.<anonymous> (/home/webpack-5/webpack.common.js:237:5)
    at Module._compile (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/webpack-5/webpack.development.js:2:16)
    at Module._compile (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/webpack-5/webpack.config.js:1:89)
    at Module._compile (/home/webpack-5/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```

Why?

I am using webpack 5.

**Comment by harlan-zw** [comment]
@lautiamkok This package acts as a bridge for the first-class support frameworks, such as Nuxt & Vue CLI. 

When using it for something custom outside of these there are far too many edge cases for me to predict and the only way I fix issues for _your_ specific issues, if if you make an issue for them. 

This is open-source, if you're going to provide feedback, make it constructive. If you don't like the package then use something else.

**Comment by lautiamkok** [comment]
@harlan-zw did I say I don't like this framework?
